server:
  port: 7070
spring:
  activemq:
    broker-url: tcp://192.168.203.144:61616
    user: admin
    password: 123
    send-timeout:
  jms:
    pub-sub-domain: false #false = queue true = topic


myqueue: boot-active-queue

